vectorstore: # URL of the remote vectorstore API
  remote:
    endpoint: "http://localhost:8000/query"
    health_endpoint: "http://localhost:8000/health"
    timeout: 5
  local:
    persist_directory: "./vectorestore/multilingual_chroma_db3" # Directory where local vectorstore is stored
    collection_name: "langchain" # Name of the vectorstore collection
    # embedding_model: "intfloat/multilingual-e5-large-instruct" # Name of the embedding model for local vectorstore
    embedding_model: "paraphrase-multilingual" # Name of the embedding model for local vectorstore
    # Ollama configuration
    ollama_base_url: "http://10.254.140.69:11434"
    ollama_embedding_model: "paraphrase-multilingual"
    use_ollama: True # Set to true to use Ollama models, false for Azure
